[package]
name = "rabitq"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
nalgebra = {version = "0.33.0", features = ["debug", "serde-serialize"]}
num-traits = "0.2.19"
rand = "0.8.5"
serde = "1.0.207"
serde_json = "1.0.124"
