[package]
name = "rabitq"
version = "0.1.0"
edition = "2021"
description = "A Rust implementation of the RaBitQ vector search algorithm."
license = "AGPL-3.0"
documentation = "https://docs.rs/rabitq"
repository = "https://github.com/kemingy/rabitq"
keywords = ["vector-search", "quantization", "binary-dot-product"]
categories = ["algorithms", "science"]

[dependencies]
anyhow = "1.0.87"
argh = "0.1.12"
aws-config = "1.5.5"
aws-sdk-s3 = "1.48.0"
bytes = "1.7.1"
env_logger = "0.11.5"
foyer = "0.11.1"
log = "0.4.22"
nalgebra = {version = "0.33.0", features = ["debug", "serde-serialize"]}
num-traits = "0.2.19"
quick_cache = "0.6.6"
rand = "0.8.5"
serde = "1.0.207"
serde_json = "1.0.124"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"

[profile.perf]
inherits = "release"
debug = true
lto = false
codegen-units = 16
panic = "unwind"
