[package]
name = "cli"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
argh = "0.1"
env_logger = "0.11"
log = {workspace = true}
rabitq = {path = "../.."}
